# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule (new syntax Hyprland 0.53+)
# windowrule = float, match:class kitty, match:title kitty

# Ignore maximize requests from apps. You'll probably like this. 
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on
